services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - api_gateway
    networks:
      - main
  api_gateway:
    build:
      context: ./
      dockerfile: ./services/api_gateway/Dockerfile
    environment:
      NATS_URL: nats://nats:4222
    ports:
      - "8000:8000"
    depends_on:
      - nats
    networks:
      - main
  projects:
    build:
      context: ./
      dockerfile: ./services/projects_service/Dockerfile
    environment:
      NATS_URL: nats://nats:4222
    depends_on:
      - nats
    networks:
      - main
  secrets:
    build:
      context: ./
      dockerfile: ./services/secrets_service/Dockerfile
    environment:
      NATS_URL: nats://nats:4222
    depends_on:
      - nats
    networks:
      - main
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--js -sd /data"
    volumes:
      - nats_data:/data
    networks:
      - main
  vault:
    image: hashicorp/vault:latest
    container_name: vault-dev
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev_root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  nats_data:
networks:
  main:
    driver: bridge
